
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */
public class SiparisUygulamasi extends javax.swing.JFrame {

    Map<String,Integer> siparisler = new LinkedHashMap<String,Integer>();
    
    public void siparisleriGoruntule()
    {
        String mesaj = "";
        int tutar = 0;
        
        if (siparisler.isEmpty())
        {
            mesaj += "Siparişiniz Bulunmamaktadır.";
        }
        else
        {
            mesaj += "Siparişleriniz\n"
                    + "-------------\n";
            
            for (Map.Entry<String,Integer> m : siparisler.entrySet())
            {
                mesaj += m.getKey() + "\n";
                tutar += m.getValue();
            }
            mesaj += "Sipariş Tutarı = " + tutar + "TL";
        }
        
        JOptionPane.showMessageDialog(this, mesaj);
        
    }
    
    
    /**
     * Creates new form SiparisUygulamasi
     */
    public SiparisUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBTavukDurum = new javax.swing.JCheckBox();
        CBCorba = new javax.swing.JCheckBox();
        CBKebap = new javax.swing.JCheckBox();
        CBAyran = new javax.swing.JCheckBox();
        CBIskender = new javax.swing.JCheckBox();
        CBKola = new javax.swing.JCheckBox();
        CBMadenSuyu = new javax.swing.JCheckBox();
        CBSalgam = new javax.swing.JCheckBox();
        BSiparis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basit Sipariş Uygulaması");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Yemekler");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("İçecekler");

        CBTavukDurum.setText("Tavuk Dürüm - 30TL");

        CBCorba.setText("Çorba - 20TL");

        CBKebap.setText("Kebap - 80TL");

        CBAyran.setText("Ayran - 5TL");

        CBIskender.setText("İskender - 80TL");

        CBKola.setText("Kola - 8TL");

        CBMadenSuyu.setText("Maden Suyu - 6TL");

        CBSalgam.setText("Şalgam - 8TL");

        BSiparis.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BSiparis.setText("Sipariş Et");
        BSiparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSiparisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSiparis, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(CBKebap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(64, 64, 64)
                                .addComponent(CBAyran, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CBTavukDurum)
                            .addGap(54, 54, 54)
                            .addComponent(CBKola, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CBIskender)
                            .addGap(80, 80, 80)
                            .addComponent(CBSalgam, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBCorba)
                        .addGap(92, 92, 92)
                        .addComponent(CBMadenSuyu)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBKebap)
                    .addComponent(CBAyran))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBTavukDurum)
                    .addComponent(CBKola))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCorba)
                    .addComponent(CBMadenSuyu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBIskender)
                    .addComponent(CBSalgam))
                .addGap(18, 18, 18)
                .addComponent(BSiparis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BSiparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSiparisActionPerformed
        
        if(CBKebap.isSelected())
        {
            siparisler.put("Kebap", 80);
        }
        else
        {
            siparisler.remove("Kebap");
        }
        if(CBTavukDurum.isSelected())
        {
            siparisler.put("Tavuk Durum", 30);
        }
        else
        {
            siparisler.remove("Tavuk Durum");
        }
        if(CBCorba.isSelected())
        {
            siparisler.put("Corba", 20);
        }
        else
        {
            siparisler.remove("Corba");
        }
        if(CBIskender.isSelected())
        {
            siparisler.put("Iskender", 80);
        }
        else
        {
            siparisler.remove("Iskender");
        }
        if(CBAyran.isSelected())
        {
            siparisler.put("Ayran", 5);
        }
        else
        {
            siparisler.remove("Ayran");
        }
        if(CBKola.isSelected())
        {
            siparisler.put("Kola", 8);
        }
        else
        {
            siparisler.remove("Kola");
        }
        if(CBMadenSuyu.isSelected())
        {
            siparisler.put("Maden Suyu", 6);
        }
        else
        {
            siparisler.remove("Maden Suyu");
        }
        if(CBSalgam.isSelected())
        {
            siparisler.put("Salgam", 8);
        }
        else
        {
            siparisler.remove("Salgam");
        }
        
        siparisleriGoruntule();
        
    }//GEN-LAST:event_BSiparisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparisUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparisUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSiparis;
    private javax.swing.JCheckBox CBAyran;
    private javax.swing.JCheckBox CBCorba;
    private javax.swing.JCheckBox CBIskender;
    private javax.swing.JCheckBox CBKebap;
    private javax.swing.JCheckBox CBKola;
    private javax.swing.JCheckBox CBMadenSuyu;
    private javax.swing.JCheckBox CBSalgam;
    private javax.swing.JCheckBox CBTavukDurum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
