
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */

class User 
{
    private String kullaniciAdi;
    private String parola;

    public User(String kullaniciAdi, String parola) {
        this.kullaniciAdi = kullaniciAdi;
        this.parola = parola;
    }

    
    
    public String getKullaniciAdi() {
        return kullaniciAdi;
    }

    public void setKullaniciAdi(String kullaniciAdi) {
        this.kullaniciAdi = kullaniciAdi;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }
    
}


public class LoginEkrani extends javax.swing.JFrame {

    private static ArrayList<User> userList = new ArrayList<User>();   

    public static ArrayList<User> getUserList() {
        return userList;
    }

    public static void setUserList(ArrayList<User> userList) {
        LoginEkrani.userList = userList;
    }
    
    /**
     * Creates new form LoginEkrani
     */
    public LoginEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBilgi = new javax.swing.JPanel();
        LParola = new javax.swing.JLabel();
        LKullaniciAdi = new javax.swing.JLabel();
        TFKullaniciAdi = new javax.swing.JTextField();
        PFParola = new javax.swing.JPasswordField();
        PButon = new javax.swing.JPanel();
        BGiris = new javax.swing.JButton();
        BKayit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Ekranı");
        setResizable(false);

        PBilgi.setBackground(new java.awt.Color(255, 255, 153));

        LParola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LParola.setText("Parola :");

        LKullaniciAdi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LKullaniciAdi.setText("Kullanıcı Adı :");

        javax.swing.GroupLayout PBilgiLayout = new javax.swing.GroupLayout(PBilgi);
        PBilgi.setLayout(PBilgiLayout);
        PBilgiLayout.setHorizontalGroup(
            PBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBilgiLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PBilgiLayout.createSequentialGroup()
                        .addComponent(LKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TFKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PBilgiLayout.createSequentialGroup()
                        .addComponent(LParola, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PFParola)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PBilgiLayout.setVerticalGroup(
            PBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBilgiLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKullaniciAdi)
                    .addComponent(TFKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PBilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LParola)
                    .addComponent(PFParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        PButon.setBackground(new java.awt.Color(255, 153, 153));

        BGiris.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BGiris.setText("Giriş Yap");
        BGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGirisActionPerformed(evt);
            }
        });

        BKayit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BKayit.setText("Kayıt Ol");
        BKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKayitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PButonLayout = new javax.swing.GroupLayout(PButon);
        PButon.setLayout(PButonLayout);
        PButonLayout.setHorizontalGroup(
            PButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PButonLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(BKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(BGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        PButonLayout.setVerticalGroup(
            PButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PButonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PButonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKayitActionPerformed
        
        RegisterEkrani register = new RegisterEkrani();
        
        register.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_BKayitActionPerformed

    private void BGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGirisActionPerformed
        
        String kullaniciGiris = TFKullaniciAdi.getText();
        String parolaGiris = new String(PFParola.getPassword());
        
        if (TFKullaniciAdi.getText().trim().equals("") || new String(PFParola.getPassword()).trim().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Lütfen Tüm Kutucukları Doldurun!");
        }
        else
        {
            for (User u : userList)
            {
                if(u.getKullaniciAdi().equals(kullaniciGiris) && u.getParola().equals(parolaGiris))
                {
                    JOptionPane.showMessageDialog(this, "Giriş Başarılı!");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Giriş Hatalı! Böyle Bir Kullanıcı Bulunamadı Lütfen Kayıt Olun!");
            
        }
        
    }//GEN-LAST:event_BGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGiris;
    private javax.swing.JButton BKayit;
    private javax.swing.JLabel LKullaniciAdi;
    private javax.swing.JLabel LParola;
    private javax.swing.JPanel PBilgi;
    private javax.swing.JPanel PButon;
    private javax.swing.JPasswordField PFParola;
    private javax.swing.JTextField TFKullaniciAdi;
    // End of variables declaration//GEN-END:variables
}
