
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */
public class StokUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulamasi
     */
    public StokUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFMarka = new javax.swing.JTextField();
        TFUrunAdi = new javax.swing.JTextField();
        TFFiyat = new javax.swing.JTextField();
        CBKategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        stokTablosu = new javax.swing.JTable();
        BEkle = new javax.swing.JButton();
        BSil = new javax.swing.JButton();
        BGuncelle = new javax.swing.JButton();
        LMesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basit Stok Uygulaması");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Kategori :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ürün İsmi :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Marka :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fiyat :");

        TFMarka.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TFUrunAdi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TFFiyat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        CBKategori.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CBKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektronik", "Gıda", "Kitap", "Ev Eşyası" }));

        stokTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Marka", "Kategori", "Fiyat"
            }
        ));
        stokTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stokTablosu);

        BEkle.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BEkle.setText("Ürün Ekle");
        BEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEkleActionPerformed(evt);
            }
        });

        BSil.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BSil.setText("Ürün Sil");
        BSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSilActionPerformed(evt);
            }
        });

        BGuncelle.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BGuncelle.setText("Ürün Güncelle");
        BGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuncelleActionPerformed(evt);
            }
        });

        LMesaj.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LMesaj.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(BEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFFiyat, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(TFMarka)
                                    .addComponent(CBKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BSil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BGuncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(LMesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CBKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BSil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(TFFiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LMesaj)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEkleActionPerformed
        
        LMesaj.setText("");
        
        DefaultTableModel model = (DefaultTableModel) stokTablosu.getModel();
        
        if (TFUrunAdi.getText().trim().equals(""))
        {
            LMesaj.setText("Ürün ismi boş bırakılamaz!");
        }
        else
        {
            Object[] ekleme = {TFUrunAdi.getText(),TFMarka.getText(),CBKategori.getSelectedItem().toString(),TFFiyat.getText()};
            
            model.addRow(ekleme);
        }
        
        TFUrunAdi.setText("");
        TFMarka.setText("");
        CBKategori.setSelectedItem("");
        TFFiyat.setText("");
        
        
    }//GEN-LAST:event_BEkleActionPerformed

    private void BGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuncelleActionPerformed
        
        LMesaj.setText("");
        
        DefaultTableModel model = (DefaultTableModel) stokTablosu.getModel();
        
        int seciliSira = stokTablosu.getSelectedRow();
        
        if (seciliSira == -1)
        {
            
            if (stokTablosu.getRowCount() == 0)
            {
                LMesaj.setText("Tabloda herhangi bir ürün bulunmamaktadır.");
            }
            else
            {
                LMesaj.setText("Güncellemek için lütfen bir ürün seçiniz.");
            }
          
        }
        else
        {
            stokTablosu.setValueAt(TFUrunAdi.getText(), seciliSira, 0);
            stokTablosu.setValueAt(TFMarka.getText(), seciliSira, 1);
            stokTablosu.setValueAt(CBKategori.getSelectedItem().toString(), seciliSira, 2);
            stokTablosu.setValueAt(TFFiyat.getText(), seciliSira, 3);
            
            LMesaj.setText("Başarıyla güncellendi!");
        }
    }//GEN-LAST:event_BGuncelleActionPerformed

    
    private void stokTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokTablosuMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) stokTablosu.getModel();
        
        int seciliSira = stokTablosu.getSelectedRow();
        
        TFUrunAdi.setText(model.getValueAt(seciliSira, 0).toString());
        TFMarka.setText(model.getValueAt(seciliSira, 1).toString());
        CBKategori.setSelectedItem(model.getValueAt(seciliSira, 2).toString());
        TFFiyat.setText(model.getValueAt(seciliSira, 3).toString());
        
        
    }//GEN-LAST:event_stokTablosuMouseClicked

    private void BSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSilActionPerformed
       
        LMesaj.setText("");
        
        DefaultTableModel model = (DefaultTableModel) stokTablosu.getModel();
        
        int seciliSira = stokTablosu.getSelectedRow();
        
        if (seciliSira == -1)
        {
            
            if (stokTablosu.getRowCount() == 0)
            {
                LMesaj.setText("Tabloda herhangi bir ürün bulunmamaktadır.");
            }
            else
            {
                LMesaj.setText("Silmek istediğiniz ürünü seçiniz!");
            }
          
        }
        else
        {
            
            model.removeRow(seciliSira);
            
            TFUrunAdi.setText("");
            TFMarka.setText("");
            CBKategori.setSelectedItem("");
            TFFiyat.setText("");
            
            LMesaj.setText("Ürün başarıyla silindi!");
            
        }
        
    }//GEN-LAST:event_BSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEkle;
    private javax.swing.JButton BGuncelle;
    private javax.swing.JButton BSil;
    private javax.swing.JComboBox<String> CBKategori;
    private javax.swing.JLabel LMesaj;
    private javax.swing.JTextField TFFiyat;
    private javax.swing.JTextField TFMarka;
    private javax.swing.JTextField TFUrunAdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable stokTablosu;
    // End of variables declaration//GEN-END:variables
}
