
import java.util.Random;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    
    private Random r = new Random();
    private int playerScore = 0;
    private int computerScore = 0;
    
    public Game() {
        initComponents();
        BRestart.setEnabled(false);
        CBPlayerChoice.setEnabled(false);
        BPlay.setEnabled(false);
        BPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock.png")));
        
        LPScore.setText(String.valueOf(playerScore));
        LCScore.setText(String.valueOf(computerScore));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFPName = new javax.swing.JTextField();
        BStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LPlayerName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LPScore = new javax.swing.JLabel();
        LCScore = new javax.swing.JLabel();
        BRestart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BPlayerIcon = new javax.swing.JButton();
        CBPlayerChoice = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        BComputerIcon = new javax.swing.JButton();
        LMessage = new javax.swing.JLabel();
        BPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPS Game");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(450, 100, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player Name :");

        BStart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BStart.setText("Start");
        BStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFPName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BStart, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BStart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        LPlayerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LPlayerName.setForeground(new java.awt.Color(255, 255, 255));
        LPlayerName.setText("Player :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score Table");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Computer :");

        LPScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LPScore.setForeground(new java.awt.Color(255, 255, 255));
        LPScore.setText("0");

        LCScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LCScore.setForeground(new java.awt.Color(255, 255, 255));
        LCScore.setText("0");

        BRestart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BRestart.setText("Restart");
        BRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LPlayerName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LCScore)
                    .addComponent(LPScore))
                .addGap(30, 30, 30))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(BRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPlayerName)
                    .addComponent(LPScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LCScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Computer");

        BPlayerIcon.setForeground(new java.awt.Color(255, 255, 255));

        CBPlayerChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Paper", "Scissors" }));
        CBPlayerChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBPlayerChoiceİtemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Player");

        LMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LMessage.setForeground(new java.awt.Color(255, 0, 0));

        BPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BPlay.setText("Play");
        BPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BPlayerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBPlayerChoice, 0, 152, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(BComputerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel8)
                    .addContainerGap(574, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CBPlayerChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(LMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BComputerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel8)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStartActionPerformed
        
        String pName = TFPName.getText();
        LPlayerName.setText(pName + " :");
        
        CBPlayerChoice.setEnabled(true);
        BStart.setEnabled(false);
        TFPName.setEnabled(false);
        BPlay.setEnabled(true);
    }//GEN-LAST:event_BStartActionPerformed

    private void CBPlayerChoiceİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBPlayerChoiceİtemStateChanged
    
        if(String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Rock"))
        {
           BPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock.png"))); 
        }
        if(String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Paper"))
        {
           BPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper.png"))); 
        }
        if(String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Scissors"))
        {
           BPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scissors.png"))); 
        }
    }//GEN-LAST:event_CBPlayerChoiceİtemStateChanged

    private void BPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPlayActionPerformed
    
        int computerChoice = r.nextInt(3);
        
        if (computerChoice == 0)
        {
            BComputerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rock.png"))); 
        }
        if (computerChoice == 1)
        {
            BComputerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper.png"))); 
        }
        if (computerChoice == 2)
        {
            BComputerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scissors.png"))); 
        }
        //**************************************************************************************************
        
        if(String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Rock") && computerChoice == 0)
        {
            LMessage.setText("Draw!");
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Rock") && computerChoice == 1)
        {
            LMessage.setText("Computer WIN!");
            computerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Rock") && computerChoice == 2)
        {
            LMessage.setText(TFPName.getText() + " WIN!");
            playerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Paper") && computerChoice == 0)
        {
            LMessage.setText(TFPName.getText() + " WIN!");
            playerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Paper") && computerChoice == 1)
        {
            LMessage.setText("DRAW!");
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Paper") && computerChoice == 2)
        {
            LMessage.setText("Computer WIN!");
            computerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Scissors") && computerChoice == 0)
        {
            LMessage.setText("Computer WIN!");
            computerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Scissors") && computerChoice == 1)
        {
            LMessage.setText(TFPName.getText() + " WIN!");
            playerScore++;
        }
        else if (String.valueOf(CBPlayerChoice.getSelectedItem()).equals("Scissors") && computerChoice == 2)
        {
            LMessage.setText("DRAW!");
        }
        //****************************************************************************************************
        
        LPScore.setText(String.valueOf(playerScore));
        LCScore.setText(String.valueOf(computerScore));
        
        if(playerScore == 3)
        {
            JOptionPane.showMessageDialog(this, TFPName.getText() + " WIN! " + "Score : " + playerScore + " - " + computerScore);
            endGame();
        }
        if(computerScore == 3)
        {
            JOptionPane.showMessageDialog(this, "Computer WIN! " + "Score : " + computerScore + " - " + playerScore);
            endGame();
        }
        
    }//GEN-LAST:event_BPlayActionPerformed

    private void BRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRestartActionPerformed
    
        TFPName.setEnabled(true);
        BStart.setEnabled(true);
        
        computerScore = 0;
        playerScore = 0;
        
        LPScore.setText(String.valueOf(playerScore));
        LCScore.setText(String.valueOf(computerScore));
        
        LPlayerName.setText("Player :");
        BRestart.setEnabled(false);
        
    }//GEN-LAST:event_BRestartActionPerformed

    public void endGame ()
    {
        TFPName.setEnabled(false);
        BStart.setEnabled(false);
        BPlay.setEnabled(false);
        CBPlayerChoice.setEnabled(false);
        BRestart.setEnabled(true);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComputerIcon;
    private javax.swing.JButton BPlay;
    private javax.swing.JButton BPlayerIcon;
    private javax.swing.JButton BRestart;
    private javax.swing.JButton BStart;
    private javax.swing.JComboBox<String> CBPlayerChoice;
    private javax.swing.JLabel LCScore;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LPScore;
    private javax.swing.JLabel LPlayerName;
    private javax.swing.JTextField TFPName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
