
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */
public class CalisanlarEkrani extends javax.swing.JFrame {

    CalisanIslemleri ci = new CalisanIslemleri();
    DefaultTableModel model;
    
    /**
     * Creates new form CalisanlarEkrani
     */
    public CalisanlarEkrani() {
        initComponents();
        model = (DefaultTableModel) TCalisanlar.getModel();
        calisanlariGoruntule();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCalisanlar = new javax.swing.JTable();
        TFAramaCubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TFDepartman = new javax.swing.JTextField();
        TFMaas = new javax.swing.JTextField();
        TFAd = new javax.swing.JTextField();
        TFSoyad = new javax.swing.JTextField();
        BCalisanEkle = new javax.swing.JButton();
        LMesaj = new javax.swing.JLabel();
        BCalisanGuncelle = new javax.swing.JButton();
        BCalisanSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calışanlar Ekranı");
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        TCalisanlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Ad", "Soyad", "Departman", "Maas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TCalisanlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TCalisanlarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TCalisanlar);
        if (TCalisanlar.getColumnModel().getColumnCount() > 0) {
            TCalisanlar.getColumnModel().getColumn(0).setResizable(false);
            TCalisanlar.getColumnModel().getColumn(1).setResizable(false);
            TCalisanlar.getColumnModel().getColumn(2).setResizable(false);
            TCalisanlar.getColumnModel().getColumn(3).setResizable(false);
            TCalisanlar.getColumnModel().getColumn(4).setResizable(false);
        }

        TFAramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFAramaCubuguKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dinamik Arama Cubuğu :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ad :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soyad :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Departman :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Maas :");

        BCalisanEkle.setText("Yeni Çalışan Ekle");
        BCalisanEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalisanEkleActionPerformed(evt);
            }
        });

        LMesaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LMesaj.setForeground(new java.awt.Color(255, 0, 0));

        BCalisanGuncelle.setText("Çalışan Güncelle");
        BCalisanGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalisanGuncelleActionPerformed(evt);
            }
        });

        BCalisanSil.setText("Çalışan Sil");
        BCalisanSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalisanSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LMesaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TFDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BCalisanSil, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TFSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BCalisanGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TFAd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BCalisanEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCalisanEkle))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCalisanGuncelle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFDepartman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCalisanSil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFMaas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LMesaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dinamikAra(String ara)
    {
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(model);
        
        TCalisanlar.setRowSorter(trs);
        
        trs.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    
    private void TFAramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFAramaCubuguKeyReleased
        
        String ara = TFAramaCubugu.getText();
        
        dinamikAra(ara);
        
    }//GEN-LAST:event_TFAramaCubuguKeyReleased

    private void BCalisanEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalisanEkleActionPerformed
        
        LMesaj.setText("");
        
        String ad = TFAd.getText();
        String soyad = TFSoyad.getText();
        String departman = TFDepartman.getText();
        String maas = TFMaas.getText();
        
        ci.calisanEkle(ad, soyad, departman, maas);
        
        calisanlariGoruntule();
        
        LMesaj.setText("Yeni Çalışan Başarıyla Eklendi!");
        
        TFAd.setText("");
        TFSoyad.setText("");    
        TFDepartman.setText("");
        TFMaas.setText("");
            
    }//GEN-LAST:event_BCalisanEkleActionPerformed

    private void BCalisanGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalisanGuncelleActionPerformed
       
        String ad = TFAd.getText();
        String soyad = TFSoyad.getText();
        String departman = TFDepartman.getText();
        String maas = TFMaas.getText();
        
        int selectedRow = TCalisanlar.getSelectedRow();
        
        if (selectedRow == -1)
        {
            if (model.getRowCount() == 0)
            {
                LMesaj.setText("Şu Anda Tabloda Herhangi Bir Çalışan Bulunmamaktadır!");
            }
            else
            {
                LMesaj.setText("Güncelleme Yapabilmek için Lütfen Bir Çalışan Seçiniz!");
            }
            
        }
        else
        {
            
            int id = (int) model.getValueAt(selectedRow, 0);
            
            ci.calisanGuncelle(id, ad, soyad, departman, maas);
            
            calisanlariGoruntule();
            
            LMesaj.setText("Calışan Başarıyla Güncellendi!");
            
        }
        
        
    }//GEN-LAST:event_BCalisanGuncelleActionPerformed

    private void TCalisanlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TCalisanlarMouseClicked
        
        int selectedRow = TCalisanlar.getSelectedRow();
        
        TFAd.setText(model.getValueAt(selectedRow, 1).toString());
        TFSoyad.setText(model.getValueAt(selectedRow, 2).toString());
        TFDepartman.setText(model.getValueAt(selectedRow, 3).toString());
        TFMaas.setText(model.getValueAt(selectedRow, 4).toString());
        
        
    }//GEN-LAST:event_TCalisanlarMouseClicked

    private void BCalisanSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalisanSilActionPerformed
        
        int selectedRow = TCalisanlar.getSelectedRow();
        
        if (selectedRow == -1)
        {
            if (model.getRowCount() == 0)
            {
                LMesaj.setText("Şu Anda Tabloda Herhangi Bir Çalışan Bulunmamaktadır!");
            }
            else
            {
                LMesaj.setText("Silme Işlemi Yapabilmek için Lütfen Bir Çalışan Seçiniz!");
            }
            
        }
        else
        {
            
            int id = (int) model.getValueAt(selectedRow, 0);
            
            ci.calisanSil(id);
            
            calisanlariGoruntule();
            
            LMesaj.setText("Calışan Başarıyla Silindi!");
            
            TFAd.setText("");
            TFSoyad.setText("");
            TFDepartman.setText("");
            TFMaas.setText("");
            
        }
        
    }//GEN-LAST:event_BCalisanSilActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void calisanlariGoruntule()
    {
        model.setRowCount(0);
        
        ArrayList<Calisan> calisanlar = new ArrayList<Calisan>();
        
        calisanlar = ci.calisanlariGetir();
        
        if (calisanlar != null)
        {
            for (Calisan c : calisanlar)
            {
                Object[] eklenecek = {c.getId(),c.getAd(), c.getSoyad(), c.getDepartman(), c.getMaas()};
                
                model.addRow(eklenecek);
            }
            
            
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanlarEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalisanlarEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCalisanEkle;
    private javax.swing.JButton BCalisanGuncelle;
    private javax.swing.JButton BCalisanSil;
    private javax.swing.JLabel LMesaj;
    private javax.swing.JTable TCalisanlar;
    private javax.swing.JTextField TFAd;
    private javax.swing.JTextField TFAramaCubugu;
    private javax.swing.JTextField TFDepartman;
    private javax.swing.JTextField TFMaas;
    private javax.swing.JTextField TFSoyad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
