
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sivri
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TAYaziAlani = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        MIDosyaAc = new javax.swing.JMenuItem();
        MIDosyaKaydet = new javax.swing.JMenuItem();
        MIKapat = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MIRenkDegistir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MIYaziTipiDegistirme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basit Notepad Uygulaması");
        setResizable(false);

        TAYaziAlani.setColumns(20);
        TAYaziAlani.setRows(5);
        jScrollPane1.setViewportView(TAYaziAlani);

        jMenu3.setText("Dosya");

        MIDosyaAc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIDosyaAc.setText("Dosya Aç");
        MIDosyaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDosyaAcActionPerformed(evt);
            }
        });
        jMenu3.add(MIDosyaAc);

        MIDosyaKaydet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIDosyaKaydet.setText("Dosya Kaydet");
        MIDosyaKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDosyaKaydetActionPerformed(evt);
            }
        });
        jMenu3.add(MIDosyaKaydet);

        MIKapat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MIKapat.setText("Kapat");
        MIKapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIKapatActionPerformed(evt);
            }
        });
        jMenu3.add(MIKapat);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Düzenle");

        jMenu2.setText("Renk");

        MIRenkDegistir.setText("Renk Değiştir");
        MIRenkDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIRenkDegistirActionPerformed(evt);
            }
        });
        jMenu2.add(MIRenkDegistir);

        jMenu1.add(jMenu2);

        jMenu5.setText("Yazı Tipi");

        MIYaziTipiDegistirme.setText("Yazı Tipi Değiştir");
        MIYaziTipiDegistirme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIYaziTipiDegistirmeActionPerformed(evt);
            }
        });
        jMenu5.add(MIYaziTipiDegistirme);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIDosyaAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDosyaAcActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        int kontrol = fc.showOpenDialog(this);
        
        if (kontrol == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            
            String icerik = "";
            
            try(Scanner scanner = new Scanner(new BufferedReader(new FileReader(file))))
            {
                while(scanner.hasNextLine())
                {
                    icerik += scanner.nextLine() + "\n";
                }
                
                TAYaziAlani.setText(icerik);
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_MIDosyaAcActionPerformed

    private void MIDosyaKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDosyaKaydetActionPerformed
        
        JFileChooser fc = new JFileChooser();
        
        int kontrol = fc.showSaveDialog(this);
        
        if (kontrol == JFileChooser.APPROVE_OPTION)
        {
            String dosyaYolu = fc.getSelectedFile().getPath();
            
            try(FileWriter writer = new FileWriter(dosyaYolu))
            {
                writer.write(TAYaziAlani.getText());
                
            } catch (IOException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_MIDosyaKaydetActionPerformed

    private void MIKapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIKapatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MIKapatActionPerformed

    private void MIRenkDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRenkDegistirActionPerformed
        
        Color color = JColorChooser.showDialog(this, "Lütfen Bir Renk Seçiniz!", Color.RED);
        
        TAYaziAlani.setForeground(color);
    }//GEN-LAST:event_MIRenkDegistirActionPerformed

    private void MIYaziTipiDegistirmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIYaziTipiDegistirmeActionPerformed
        
        JFontChooser fc = new JFontChooser();
        
        int kontrol = fc.showDialog(this);
        
        if (kontrol == JFontChooser.OK_OPTION)
        {
            Font font = fc.getSelectedFont();
        
            TAYaziAlani.setFont(font);
        }
        
        
    }//GEN-LAST:event_MIYaziTipiDegistirmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIDosyaAc;
    private javax.swing.JMenuItem MIDosyaKaydet;
    private javax.swing.JMenuItem MIKapat;
    private javax.swing.JMenuItem MIRenkDegistir;
    private javax.swing.JMenuItem MIYaziTipiDegistirme;
    private javax.swing.JTextArea TAYaziAlani;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
